mariadb:
  image: "mariadb"
  environment:
    - "MYSQL_ROOT_PASSWORD=thesecretsauce"
    - "MYSQL_DATABASE=kdaemon"
    #note: in order to get mariadb and kdaemon to sex properly, I have generally been docker compose up weave expose (mariadbcontainerid), then taking that ip address and putting it statically into the env vars for kdaemon.  It's not yet ideal.  
#rancher@rancher:~$ weave stop-proxy
#rancher@rancher:~$ weave expose > weaveip
#rancher@rancher:~$ cat weaveip
#10.33.8.8
#rancher@rancher:~$ weave launch-proxy -H 10.33.8.8:2375
#2e297af167c8b24d1ac9f2b06caf010c126f922483e8820446603e2a70e03413
kdaemon:
  image: "superordinate/kdaemon"
  links:
    - mariadb
  environment:
    - BIND_IP=0.0.0.0
    - API_PORT=1337
    - UI_PORT=13337
    - MYSQL_HOST=10.33.0.2
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=thesecretsauce
    - MYSQL_DBNAME=kdaemon
  ports:
    - 0.0.0.0:1337:1337
    - 0.0.0.0:13337:13337
  labels:
    - io.rancher.os.after mariadb
prometheus:
  image: prom/prometheus:latest
  ports:
    - 0.0.0.0:9090:9090
  links:
    - "cadvisor:cadvisor"
  labels: 
    - "name=prometheus"
    - "description=Core of Prometheus"
cadvisor:
  image: google/cadvisor:latest
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:  
    - 0.0.0.0:8080:8080
